---
  - import_tasks: server_setup.yml

  - import_tasks: install_percona.yml
    when: mysql_variant == 'percona'

  - import_tasks: install_mysql.yml
    when: mysql_variant == 'mysql'

  - import_tasks: install_mariadb.yml
    when: mysql_variant == 'mariadb'

  - import_tasks: set_root.yml

  - import_tasks: sakila.yml
    when: with_data 


