---
  - name: install python selinux bindings
    yum: name=libselinux-python state=present

  - name: install mysql python
    yum: name=MySQL-python state=present

  - name: copy over my.cnf file
    copy: src=roles/database/files/my.cnf dest=/etc/my.cnf owner=root mode=0644
    when: mysql_variant != 'mariadb'

  - name: Install Percona Repo
    yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm state=present
    when: mysql_variant != 'mariadb'
