---
  - hosts: "{{ hosts }}"
    remote_user: vagrant
    become: true
    become_user: root
    vars:
      mysql_variant: percona
      mysql_version: '57'
      new_pass: MyNewPass6^
    roles:
      - database